version: '3'
services:
  node:
    build: .
    tty: true
    container_name: 'next'
    environment:
      - NODE_ENV=development
    volumes:
    - ./app:/app
    command: sh -c "npm run dev"
    ports:
    - "3000:3000"